version: '3'
services:
  kibana:
    image: docker.elastic.co/kibana/kibana:6.6.1
    volumes:
      - ./kibana.yml:/usr/share/kibana/config/kibana.yml
    ports:
      - 5601:5601
    networks: 
      - all-tier
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:6.6.1
    ports:
      - 9200:9200
    environment:
      - "discovery.type=single-node"
    networks: 
      - all-tier
networks:
  all-tier: